### ISSUE TITLE
*Principles* (early chapter)

### ISSUE THREAD

**Issue by kieranpotts** [craftingpress/crafting-css#6]
# Principles

These are the software design principles that have most influenced the [architecture](architecture.md), [naming conventions](conventions.md) and [coding style](style-guide.md) of Nero CSS.

* [Embrace Constraints](#embrace-constraints)
* [Encapsulation](#encapsulation)
* [Loose Coupling](#loose-coupling)
* [Defensive Programming](#defensive-programming)
* [Predictability](#predictability)
* [Separate of Concerns](#separation-of-concerns)
* [Single Responsibility Principle](#single-responsibility-principle)
* [Composition](#composition)
* [The Open/Closed Principle](#the-openclosed-principle)
* [Don't Repeat Yourself](#dont-repeat-yourself)
* [Progressive Enhancement](#progressive-enhancement)

## Embrace Constraints

It has become best practice to use only class-based selectors in CSS. The primary benefit of this approach is it reduces the influence of the style cascade. Compare the two examples below. 

```css
/* Global reset */

* {
  color: hsl(0, 0%, 10%);
  line-height: 1;
  list-style: none;  
}
```

```css
/* Example 1 */

ul {
  color: hsl(0, 0%, 25%);
  font-size: 1.2rem;
  line-height: 1.4;
  list-style: square inside;
}

nav ul {
  color: initial; /* Repetition */
  font-size: 1rem;
  line-height: 1;  /* Repetition */
  list-style: none;  /* Repetition */
}
```

```css
/* Example 2 */

.list {
  color: hsl(0, 0%, 27%);
  font-size: 1.2rem;
  line-height: 1.4;
  list-style: square inside;
}

.nav-list {
  font-size: 1rem;
}
```

Both examples achieve the same result, but the second has fewer lines of code.  In the first example, the ``nav ul`` selector inherits the properties set via the ``ul`` selector. The designer wants only to change the ``font-size`` of lists within navigation sections, but must also reset inherited properties such as ``color``, ``line-height`` and ``list-style``. In the second example, no styles cascade between the class-based selectors. This means there is less repetition because the CSS author does not need to reset any unwanted inherited properties.

As well as being more verbose, the first example is also more brittle. Design changes that are intended to target one part of the UI can unexpectedly seep through to other, unrelated parts. Type selectors are notoriously leaky.

There are many other good things to be said for the class-based approach to writing CSS:

- If we use classes as the exclusive contract between HTML and CSS we will benefit from very granular control over the presentation of individual bits of the GUI.
- Our CSS selectors will be less dependent upon particular HTML structures, allowing us to change much more HTML before triggering wider CSS refactoring. 
- And we will rarely need to unwind unwanted inherited styles, because if we use classes for everything then naked element types need be given few default styles in the first place.

Some would argue that greater dependence on classes increases the coupling between HTML and CSS. This is wrong. Classes are intended exactly for this purpose. Classes are an abstraction layer linking two separate concerns, the equivalent of hooks in event-driven programming.

The class-based approach is not perfect:

- We don't benefit so much from the convenience and efficiency of CSS's cascading inheritance model.
- Class-based designs tend to have more rulesets overall, meaning browsers have more work to do to resolve the final presentation of each DOM node.
- HTML documents end up being riddled with classes.

There is a balance to be found between harnessing the benefits of the cascade, by assigning lots of defaults for naked elements, and locking things down, by using classes as the primary API linking HTML to CSS.

The sweet spot between these two extreme approaches will vary from project to project, and over the lifecycle of an individual project. But a good starting point for implementation of any web-based GUI is to create a custom "reset" that sets default presentations for typography, hyperlinks, tables, input controls, buttons, and indeed for every visible element type that will be used by the application.

These defaults will trickle through to every context in which the elements are used, and that's okay. We must accept that we will sometimes need to reset inherited defaults. If we find ourselves resetting lots of stuff, we can iterate – in a restrained and considered way – towards reducing the number of properties applied via naked type selectors and increasing our use of classes.

Embracing the constraints of the style cascade from the outset, rather than trying desperately to work around it, helps to keep our creative impulses in check. It encourages us to build visual style guides around the limited number of native HTML elements rather than the infinite possibilities afforded by classes. The natural constraints of the cascade make it difficult to create anything except supremely consistent designs that are quickly rendered in the browser. That's a good place to start, at least.

Nero CSS ships with a fairly aggressive reset style sheet that makes good pragmatic use of the CSS inheritance model for some global concerns such as typography and colors. At the same time, the reset helps CSS authors to control the cascade by providing a more stable, predictable foundation on which to build a class-based design.

## Encapsulation

The underlying cause of the ills of the CSS inheritance model is that it makes everything global. When a browser is presented with a new element to render, it will traverse every selector in every style sheet looking for matches. Thus every ruleset has the potential to be applicable to everything on the web page.

Until we get a standard, reliable scoping mechanism for CSS, we must devise our own scoping mechanism. The answer is to use classes as namespaces. Namespacing helps to stop styles from leaking in and out of distinct parts of an interface, like sidebars and footers.

Consider the following example.

```css
.sidebar a {
  background: hsl(195, 5%, 80%);
  color: hsl(0, 0%, 100%);
  padding: 0.25em 0.5em;
  text-decoration: none;
}
```

Hyperlinks nested in our web site's sidebar will of course inherit the default properties assigned for all anchor (``<a>``) elements. The above ruleset then modifies and extends those defaults, but only for hyperlinks that are located within the sidebar. The containing ``sidebar`` class acts as a namespace, encapsulating certain presentations within a particular section of the document.

But what would happen if we added to the same sidebar, say, a calendar component? The above ruleset would apply itself to links within the calendar's markup, too. That is almost certainly not what the CSS author had intended.

One of the key principles of class-based encapsulation is to be very precise and intentional about what we select for styling. One possible way to achieve this is to use class-based namespacing in conjunction with descendant selectors to zero-in on precisely the things that we want to target.

```css
.sidebar nav > ul a {}
.sidebar .calendar table a {}
```

But new problems arise with lengthy descendant selectors. The rulesets become dependent upon there being very specific HTML structures in place. In the example above, the presentation of the navigation links depends on them being nested inside an unordered list, which must be the immediate descendant of a ``<nav>`` element, which in turn must be nested in something with the class ``sidebar``. This is a simplified example, but it serves to make the point: if the HTML changes, the design breaks.

Another problem with long descendant selectors is their high specificity. Imagine if later we wanted to vary the presentation of certain ``<a>`` instances that appear within the calendar component. We'd have to create new selectors that have an even higher specificity to compete with these existing selectors. High-specificity selectors make it difficult to modify and extend things because the only way to do so is to wage specificity wars, selector against selector.

There is one other good reason to avoid complex combinator selectors. Consider the following example.

```css
.sidebar section:first-of-type h2 + p {}
```

Modern browsers evaluate selectors like this very quickly indeed. Performance is no longer a big issue when it comes to CSS selector formats. But complex combinator selectors are still pretty tricky for the silly old human brain to evaluate. It will probably take you a few moments to figure out exactly what things this ruleset affects. (Answer: the first paragraph placed immediately after every ``<h2>`` element in the first ``<section>`` of all sidebars.)

This is just one selector. Imagine mentally mapping a 1,000-line CSS file full of stuff like this. For our own sanity as much as anything else, we need a looser coupling of CSS to HTML.

## Loose Coupling

The mark of a maintainable software program is when developers can easily change things in one part of the codebase and be confident they have not inadvertently broken things in other parts. In front-end web engineering this translates to being able to alter the source order of an HTML document without triggering major CSS refactoring.

Here's our selector again for hyperlinks in a sidebar navigation list.

```css
.sidebar nav > ul a {}
```

And here's the selector rewritten to be more loosely coupled to the HTML without compromising on the level of encapsulation. It uses fewer descendant selectors but compensates with more targeted encapsulation classes.

```css
.sidebar-menu a {}
```

We could go further still and apply the class directly to each nested ``<a>`` element within the sidebar menu. We would do away with the descendant selector altogether and the presentation of the sidebar menu links would still be adequately encapsulated – more so, in fact.

```css
.sidebar-menu-link {}
```

Applying classes directly to the things that we want to look different from their default presentation has numerous benefits. It gives us a bit more flexibility to move things about and to add new stuff to the HTML. In this case we could easily add new links to the sidebar menu that are styled differently to the existing links. The designer's intention is clearer, too. The classes applied to elements describe exactly what those elements should look like, making it easier to tell if the rendered effect is intentional or a mistake. When debugging a rendering error, there's no need to traverse up the whole DOM tree and aggregate each of the affected element's inherited styles. The element's own classes tell you everything you need to know.

The only real downside of this highly targeted approach to the application of styles is that we will have a lot more classes littered about our HTML markup. In this case the ``sidebar-menu-link`` class will be duplicated on every link in the sidebar menu. As with everything in CSS, nothing is perfect. There is a balance to be found. Our preference should be to assign classes directly to the elements that we want to differentiate from their default presentation. A flat hierarchy of class selectors will make our web designs easier to maintain and scale in the long-term.

But sometimes it will be perfectly sensible to push encapsulation classes up one or two levels in the DOM tree, if doing so provides a better balance between encapsulation and decoupling of HTML from CSS. Attaching encapsulation classes to ancestors is certainly acceptable for UI components made from lists and tables and anything else where the HTML structure is unlikely to change.

## Defensive Programming

It has become common practice to use plain class selectors without type qualification. This:

```css
.xs { font-size: 0.8rem; }
.s { font-size: 1rem; }
.m { font-size: 1.4rem; }
.l { font-size: 1.8rem; }
.xl { font-size: 2.4rem; }

.bullets { list-style: square inside; }
.no-bullets { list-style: none; }
```

Not this:

```css
p.xs { font-size: 0.8rem; }
p.s { font-size: 1rem; }
p.m { font-size: 1.4rem; }
p.l { font-size: 1.8rem; }
p.xl { font-size: 2.4rem; }

ul.bullets { list-style: square inside; }
ul.no-bullets { list-style: none; }
```

Plain class selectors provide the loosest coupling between HTML and CSS, and they make classes the most reusable. One of the disadvantages is that it is not always obvious, from reading the CSS alone, where in the HTML each class is supposed to be used.

Inline annotations can help clarify that. 

```css
/* Usage: <p class="xs|s|m|l|xl"> */
.xs { font-size: 0.8rem; }
.s { font-size: 1rem; }
.m { font-size: 1.4rem; }
.l { font-size: 1.8rem; }
.xl { font-size: 2.4rem; }

/* Usage: <ul class="(no-)bullets"> */
.bullets { list-style: square inside; }
.no-bullets { list-style: none; }
```

But still, classes can be misused, applied to elements that the CSS author had not tested and accounted for.

The principle of defensive programming dictates that we should design components of our software programs for explicit purposes and to report errors when components are misused, so developers are forced to fix their code before errors snowball into even nastier bugs. For example, we might throw exceptions when a function receives an input argument of a type that it is not expecting.

In some — but not all — cases, this is a good principle to apply to CSS, too. Type qualification of classes can be a good thing _in limited circumstances_. Qualifying our class definitions with element types means we, as CSS authors, are being explicit about the contexts in which our classes are meant to be used. The CSS is more self-documenting and the CSS API (whose endpoints are classes) is better defended against misuse. Also, restricting the use of classes to a narrow set of HTML elements means we are exposing a finite API and so we are more able to aim for 100% test coverage of all the different contexts in which all our CSS classes can be used.

Where classes are designed to be usable on multiple element types, we can use standard CSS nesting syntax to keep our code neat and tidy.

```css
p, ul, ol {
  &.xs { font-size: 0.8rem; }
  &.s { font-size: 1rem; }
  &.m { font-size: 1.4rem; }
  &.l { font-size: 1.8rem; }
  &.xl { font-size: 2.4rem; }
}

ul {
  &.bullets { list-style: square inside; }
  &.no-bullets { list-style: none; }
}
```

Now, if a developer adds the ``xs`` class to an ``<h1>`` or any other element type, no harm will be done. The above ruleset will not get selected and it's ``font-size`` property will not be applied. The developer's mistake fails silently rather than loudly, but this is about as defensive as we can get with CSS.

In Nero CSS, we apply type qualification only to a handful of utility classes, never layout or component classes (see the documentation on [Nero CSS architecture](architecture.md)). Utility class declarations are type-qualified only where the clases are designed for specific purposes, such as the styling of lists, input controls and buttons.

Some utility classes are intended to be usable on just about anything. We are clear that that's the case, by qualifying such universal classes with the universal selector (*).

```css
*.clearfix {}
```

Type qualification of class declarations makes less sense for component and layout classes. For example, although the ``Button`` component class is intended to be applied to either ``<button>`` or ``<a>`` elements, this is __not__ enforced in the CSS with type-qualified class declarations. The reason is that if we did that, then we couldn't use utility classes to override the default styles for buttons. Type-qualified classes have higher specificity than plain class selectors.

```css
button.Button {
  background: lightgrey;
}

.background-midgrey {
  background: midgrey;
}

<!-- The background of this button will be lightgrey, not midgrey. -->
<button class="Button background-midgrey">
```

As for layout classes, consumers can assume that they are meant to be used on ``<div>`` elements or any of the semantic sectioning elements: ``<main>``, ``<header>``, ``<footer>``, ``<article>``, ``<aside>``, ``<address>``, ``<nav>`` and ``<section>``. It's pretty handy to have the flexibility to swap around these elements in the markup – for example replacing a ``<section>`` with an ``<aside>`` – without needing also to refactor the CSS.

## Predictability

Classes help us to scope styles to particular bits of markup. But there is still a real possibility of leakage if we choose class names that are too generic. Consider the following example.

```html
<p class="tagline">Tagline</p>
<h1 class="headline">Headline</h1>
<p class="meta">Author, Date</p>
```

Here are the selectors we'd write to target these elements.

```css
.headline {}
.tagline {}
.meta {}
```

Now, in a large project it is entirely conceivable that the classes ``tagline`` and ``meta`` could turn up elsewhere. And that may result in styles leaking out from one part of the UI and into another unrelated part. That's fine if we had intended ``tagline`` and ``meta`` to be global classes, usable in lots of different contexts. But such inclusive terminology should not be used where styles are meant to be locked down to particular parts of the interface.

A robust, scalable CSS codebase is one where all of the classes behave predictably. Just by reading the name of a class among some markup, we should be able to confidently predict what sort of presentational effects it discharges and the sphere of the class's influence. We should understand exactly what other parts of the application may depend upon the class. And we should understand what would be the consequences of removing the class from the document.

The bigger the project, and the more complex the visual design, the more important it is that classes behave predictably. The way we achieve this is through consistent execution of a solid class naming methodology.

## Separation of Concerns

The problem with classes is that they are made to do so much stuff. Some classes set the position of things. Some modify the default presentation of individual elements. Some encapsulate the styles of larger UI components such as navigation bars and modal popups. Some act as targets for DOM queries in JavaScript. Some get dynamically added to documents for the purpose of feature detection (à la Modernizr). Hell, classes have even been used as meta data (think microformats).

Consider the following markup snippet.

```html
<div class="header">
```

What does the class ``header`` do here, exactly? Does it position the ``<div>`` element on the page? Does it change the design of the ``<div>``, giving it a background, borders, margins and padding? Does it set the presentation of content that is nested within the ``<div>``? Does it act as a target for DOM queries in JavaScript? Of course, we don't know. To find out we'd have to research the class by looking it up in the style sheets or using the browser console.

In a more ideal world we should know the answers to these questions from the name of the class alone. Just by reading the source of an HTML document we should know:

- What each class in the markup does.
- Where each class has come from (which CSS library, which module within that library).
- Where else in the document a class might be used.
- The relationships between classes.
- What will be the consequences of removing a class.

We achieve this by using different naming conventions to distinguish between classes that fulfil different roles.

Class naming conventions are the backbone of modern web design methodologies. Consider the following example, which represents the basic structure of class names in a widely used convention called Block Element Modifier, or BEM.

```css
.component-name {}
.component-name--modifier-name {}
.component-name__sub-object {}
.component-name__sub-object--modifier-name {}
```

BEM is a superb system for categorising the roles of classes and for modularising front-end code. Clarity trumps brevity and tidyness. BEM produces verbose and somewhat ugly class names, and it increases the learning curve — the onboarding effort required before new contributors can be productive. But the benefits are huge. A robust class naming convention such as BEM — if implemented properly and consistently — produces expressive and highly scalable CSS.

## Single Responsibility Principle

It is easier to give a class a meaningful name if it does only one very specific thing. Specialist classes are the most predictable of classes, because their names tend to be self-explanatory. I think we can be pretty confident what a class called ``box-shadow`` will do. It is less clear what a class called ``box`` might do. It might apply a box shadow, but equally it could apply borders, padding, backgrounds and maybe even alter the presentation of nested typographic elements and controls. It might do all of these things and more at once.

Classes that are focused on one particular concern tend also to be more useful. We can often reuse specialist classes in lots of different places. Consider the following example.

```css
.alert {
  background: hsl(0, 100%, 50%);
  color: hsl(0, 0%, 100%);
  font-size: 1.6rem;
  font-weight: 700;
  left: 0;
  padding: 0.5em 2em;
  right: 0;
  text-transform: uppercase;
  top: 0;
}
```

This ruleset styles and positions a warning message at the top of the screen. Harmless enough. But suppose that down the road we wanted to use the same component but in a different location. Alas we can't reuse our existing ``alert`` class because it has been designed for placement in one specific corner of the layout. The problem is we're trying to make this class do too much. It sets look-and-feel as well as layout and position. So better to split apart these concerns into separate components.

```css
.layout-alerts {
  left: 0;
  position: absolute;
  right: 0;
  top: 0;
}

.alert-box {
  background: hsl(0, 100%, 50%);
  color: hsl(0, 0%, 100%);
  font-size: 1.6rem;
  font-weight: bold;
  padding: 0.5em 2em;
  text-transform: uppercase;
}
```

What we've got now is a class called ``layout-alerts`` that positions a container element but does not style any content. And we've got an ``alert-box`` class that _does_ style nested content and wraps it up in a visual box. By using these two classes together we can compose a presentation that matches that achieved by our original ``alert`` class.

```html
<div class="layout-alerts alert-box">
    ... 
</div>
```

The point is we can now reuse the ``alert-box`` component in other places. Here it is in the web site's sidebar:

```html
<div class="layout-sidebar alert-box">
    ...
</div>
```

## Composition

We could go further. We could delegate responsibility for other aspects of the presentation to even more classes. Let's create a class called ``warning`` that sets the font colour and background of the alert box. And let's create a class called "shout" that transforms text to upper case and renders it in big, bold type.

```css
.warning {
  background: hsl(0, 100%, 50%);
  color: hsl(0, 0%, 100%);
}

.shout {
  font-size: 1.6rem;
  font-weight: bold;
  text-transform: uppercase;
}
```

Now our original "alert-box" class has very little left to do.

```css
.alert-box { 
  padding: 0.5em 2em; 
}
```

In fact, this doesn't make sense anymore. Let's instead create some specialist utility classes to apply padding.

```css
.padding-vertical-narrow {
    padding-bottom: 0.5rem;
    padding-top: 0.5rem;
}

.padding-horizontal-wide {
    padding-left: 2rem;
    padding-right: 2rem;
}
```

The final presentation is composed from multiple classes.

```html
<div class="layout-alerts padding-vertical-narrow padding-horizontal-wide warning shout">
    ...
</div>
```

This is so much more flexible. If later we wanted to vary the presentation of a single alert box instance, we'd just make new classes. We might want to give one specific alert box instance some rounded corners, say.

```css
.rounded-corners { 
  border-radius: 5px; 
}
```

Or what about a box shadow?

```css
.box-shadow { 
  box-shadow: 7px 7px 5px 0 hsl(0, 0%, 20%); 
}
```

And here's a class called ``success`` that replaces ``warning``, changing the background colour of an alert box.

```css
.success {
  background: hsl(120, 100%, 25%);
  color: hsl(0, 0%, 100%);
}
```

Breaking down designs to a very granular level like this allows us to compose lots of different designs from the same base components. We can create a multiplicity of alert box designs. And we can reuse many of the same classes to compose entirely unrelated UI components. Here are some of our newly-forged specialist classes being reused to compose the presentation of a modal popup:

```html
<div class="popup success rounded-corners box-shadow">
```

Imagine if the ``rounded-corners`` class also set borders, padding and margins. It would be far less useful. The more specialised the class, the more frequently it can be recycled in the composition of different bits of a UI.

## The Open/Closed Principle

Composing complex designs from lots of small, specialised components speeds up the web design process because less CSS needs to be written and maintained. It also makes for a more stable codebase. Specialist classes tend not to need updating as much as comprehensive classes.

Consider again the example of the alert box, above. If we wanted to change any aspect of the presentation of an alert box, we'd just extend the base presentation by adding new classes into the mix. We wouldn't need to modify any of the existing classes.

And that's very handy. Once a class is forged and imprinted in our UI pattern library, we don't want to have to go back and change it. Doing so may have implications for lots of things that already use that class. And in mature projects that could create a lot more work for sleep-deprived web designerss.

As a programmer would say, classes should be open for extension but closed for modification.

## Don't Repeat Yourself

The more that we break down a design into small, abstracted, portable components, the less frequently we will need to repeat declarations of the same CSS properties and values. Instead we just reuse the classes that set those properties and values.

But that doesn't help us when we establish the default presentation of individual element types. Consider the following example.

```css
h2 {
  font-size: 2rem;
  line-height: 1.2;
  margin-top: 2em;
  margin-bottom: 1em;
}

h3 {
  font-size: 1.4rem;
  line-height: 1.2;
  margin-top: 2em;
  margin-bottom: 1em;
}

p {
  font-size: 1.4rem;
  line-height: 1.2;
  margin-bottom: 1em;
}
```

Writing one selector per element like this is the easiest way to configure the default presentation of element types. But there are lots of duplicated properties in this example, aren't there? All three share the same ``line-height`` and ``margin-bottom`` values; the ``<h2>`` and ``<h3>`` elements share the same ``margin-top`` value; and the ``<h3>`` and ``<p>`` elements share the same font-size.

To eliminate this duplication, we have two options. We could delegate responsibility for recurring default properties to classes. Or we might reorganise type selectors around properties instead of elements, like this:

```css
h2        { font-size: 2rem; }
h3, p     { font-size: 1.4rem; }

h2, h3, p { line-height: 1.2; }

h2, h3    { margin-top: 2em; }
h2, h3, p { margin-bottom: 1em; }
```

In this example the number of non white space characters has reduced by 40%. In some projects we have achieved savings of nearly 80%, just by reorganising type selectors around properties rather than elements.

Although we should work hard to maintain DRY ("Don't Repeat Yourself") style sheets, we should not be afraid to allow things to get a little WET ("Write Everything Twice") here and there. If two unrelated UI components happen to have similar visual characteristics, that is purely circumstantial and it is not necessary that the duplicated properties be declared via the same selector. There's nothing wrong with a little bit of repetition if it's the simplest solution.

## Progressive Enhancement

Writing media queries alongside the base selectors that they extend is the simplest, clearest solution to implementing responsive design. Nero CSS adopts the mobile-first approach whereby the default presentation is optimised for mobile then progressively enhanced for larger viewports and different types of output device.

Mobile-first web design makes extensive use of ``min-width`` (and sometimes ``min-height``) media query parameters. In the following example the padding and margins set via the ``ArticleBox`` class are steadily increased as the viewing window gets bigger. And on screens wider than 1200px (75rem), boxed content is floated to the right edge of its container.

```css
.ArticleBox {
    border: 1px solid hsl(0, 0%, 80%);
    margin: 1rem 0;
    padding: 0.5rem 1rem;
}

@media screen and (min-width: 56.25rem) {
    .ArticleBox {
        margin: 2rem 0;
        padding: 1rem 2rem;
    }
}

@media screen and (min-width: 75rem) {
    .ArticleBox {
        border-width: 2px;
        clear: right;
        float: right;
        margin: 0 0 5rem 2rem;
        padding: 2rem 4rem;
    }
}
```

The reverse approach – designing for desktop first then trying to get things to collapse down to mobile – uses ``max-width`` and ``max-height`` parameters instead.

```css
.ArticleBox {
    border: 2px solid hsl(0, 0%, 80%);
    clear: right;
    float: right;
    margin: 0 0 5rem 2rem;
    padding: 2rem 4rem;
    width: 30%;
}

@media screen and (max-width: 75rem) {
    .ArticleBox {
        border-width: 1px;
        float: none;
        margin: 2rem 0;
        padding: 1rem 2rem;
        width: auto;
    }
}

@media screen and (max-width: 56.25rem) {
    .ArticleBox {
        margin: 1rem 0;
        padding: 0.5rem 1rem;
    }
}
```

Notice how much more code there is. Because desktop designs tend to be more complicated than mobile ones, we have to unset a whole bunch of stuff to get the desktop view to collapse nicely to mobile. The mobile-first approach is much more convenient. We make greater use of the default presentation of HTML elements and we only ever add stuff that is not going to be reset again.

The mobile-first approach works beautifully in all modern browsers. Legacy browsers that do not support media queries (Internet Explorer < 9) will render the default mobile view.

The mobile-first, progressive enhancement approach to web design brings a whole bunch of other benefits. It means that smaller devices – which typically have the slowest processors – have only to render the simplest versions of our web GUIs. Mobile devices can ignore a whole bunch of stuff in our CSS files. Mobile-first design also forces us to place content in its logical order in the HTML document and not have the source order dictated by the desire to achieve a particular layout on big screens. This constraint is good for accessibility.

***************************************************

TODO:

(Principles of Good Programming - Extended CSS Languages help to achieve some of these good practices, by reducing duplication in our code, for example.)

(notes)

Orthogonality: in programming language design this is the ability to use various language features in arbitrary combinations with consistent results.

Reduces interdependence.
Improves composability.
Separates concerns.
Reduces collisions.
Removes side effects.
Good litmus test: can we reorder imports?

How well can we arbitrarily combine things?
The implication is that they don't rely on one another.
The hallmarks of a flexible and modular system.

Well-scoped selectors improve orthogonality.

***

The Open/Closed Principle: Software entities should be open for extension but closed for modification... Once completed, the implementation of a class could only be modified to correct errors; new or changes features would require that a different class be created. That class could reuse coding from the original class through inheritance.

Never change anything at its source.
Avoid the Domino Effect.
Doing so causes visual regressions.
Hard to keep track of knock-on effects.
Always make changes via extension / addition.
Possibly the most useful principle for dealing with other people's code!

A safe way to make changes.
Everything gets opted into explicitly.
Prevents changes from happening one-sidedly; the developer has to add the class into the markup as well.
A second layer of safety: changes can't be actioned from one place alone.
Build things forward.
Safe way of working with legacy.

***

Cyclomatic Complexity: A software metric used to indicate the complexity of a program. It is a quantitative measure of the number of linearly independent paths through a program's source code.

It's basically just the number of ifs/elses.
A form of static analysis.
Counting the number of paths through a program.
The amount of potential outcomes given certain conditions.
Higher complexity is bad: simpler is always better.

In CSS, this sort of selector creates cyclomatic complexity:

div.main section.content h1 a span {}

Deeply nested and qualified selectors are bad.
They carry a high Cyclomatic Complexity.
Reduce by using much shorter selectors.
Get straight to the point.
Remove as many conditions and caveats as possible.
Start with the correct subject - i.e. the bit of DOM that you are actually targetting should be on the left, not the right, of the selector.

***

Immutability: An immutable object is one whose state cannot be modified after it is created.

Provides confidence.
Makes things predicable.
Helps debugging.
Reduces cognitive overhead.
Removes caveats, states and conditions.

This is a particularly big problem in CSS where parts of the codebase are easily able to mutate other parts, leading to unpredictable outcomes, unexpected side effects.

***

Separation of Concerns:

Each thing responsible for itself and nothing more.
Reason about and study features in isolation.
In CSS:
Only bidn CSS onto CSS_based classes only.
Don't write DOM-like selectors.
Don't bind CSS onto data- attributes
Don't bind JS onto CSS classes.
Don't bind CSS to accessibility hints (e.g. aria- attrs).

***

The Single Responsibility Principle: Every class should have responsibility over a single part of the functionality provided by the software, and that responsibility should be entirely encapsulated by that class.

Do one thing, one thing only, and do it well.
Break bigger monoliths into individual concerns.
Easier to reason about.
Provides higher composability.

***

Confusion:
DRY in source, not in production.
Not about avoiding repetition
It's about avoiding repeating yourself.
Automation of repetition is fine!

If you manually type a declaration 50 times in a project, you are repeating yourself: this is not DRY. If you can generate that declaration 50 times without having to manually repeat it, this is DRY: you are generating repetition without actually repeating yourself. This is quite a subtle but important distinction...

Don't DRY if it is repeated coincidentally.
Repetition in compiled code is fine.
Just avoid duplicating data in source.
Going too far creates awkward and confusing structures in your code.

Use a preprocessor to store key data in variables.
Make use of mixins to generate repetition for you.
Abstract design patterns out into reusable objects.
Do not DRY anything that is purely coincidental.
Repetition is better than the wrong abstraction.

***

Single Source of Truth: The practice of structuring information models and associated schemata such that every data element is stored exactly once.

The more philosophical principle behind DRY. Key data should exist once in source. Increases confidence. Prevents anomalies and disparity. Makes changes simpler. Keeps your house in order.

***

Don't Repeat Yourself: "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system.

Every discrete piece of information should exist only once. You shouldn't need to make the same change several times. Repetition is extra overhead: more to maintain, to go wrong. Increases cognitive overhead. And contributes to bloat.
